"""set imagemodel rel

Revision ID: adea7fdc5d33
Revises: b9f1d2842182
Create Date: 2022-08-12 11:37:13.549596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adea7fdc5d33'
down_revision = 'b9f1d2842182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
