"""create imagestable

Revision ID: b9f1d2842182
Revises: 
Create Date: 2022-08-12 11:14:30.365591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f1d2842182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productsimage_Product_id_fkey', 'productsimage', type_='foreignkey')
    op.create_foreign_key(None, 'productsimage', 'products', ['Product_id'], ['product_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productsimage', type_='foreignkey')
    op.create_foreign_key('productsimage_Product_id_fkey', 'productsimage', 'users', ['Product_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
